version: '3'
services:
  postgres:
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 555666999
      POSTGRES_DB: testbdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 555666999
    restart: unless-stopped

volumes:
  postgres-data: